apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api-service
  labels:
    app: stock-api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-api-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stock-api-service
    spec:
      containers:
      - name: api
        image: IMAGE_TO_REPLACE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: DB_HOST
          value: "cockroachdb"
        - name: DB_PORT
          value: "26257"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: ""
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: dbname
        - name: DB_SSL_MODE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_SSL_MODE
        envFrom:
        - configMapRef:
            name: stock-api-service-config
        - configMapRef:
            name: api-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
      restartPolicy: Always