apiVersion: v1
kind: Service
metadata:
  name: stock-data-service
  labels:
    app: stock-data-service
spec:
  selector:
    app: stock-data-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort